import type {
	ActionFluentIconNameV0,
	ActionIconV0,
} from "@amll-ttml-tool/plugin-api";
import {
	AddRegular,
	ArrowDownRegular,
	ArrowLeftRegular,
	ArrowResetRegular,
	ArrowRightRegular,
	ArrowUpRegular,
	CheckmarkCircleRegular,
	CheckmarkRegular,
	ChevronDownRegular,
	ChevronLeftRegular,
	ChevronRightRegular,
	ChevronUpRegular,
	ClockRegular,
	CopyRegular,
	CutRegular,
	DeleteRegular,
	DismissRegular,
	DocumentRegular,
	EditRegular,
	ErrorCircleRegular,
	EyeOffRegular,
	EyeRegular,
	type FluentIcon,
	FolderOpenRegular,
	HistoryRegular,
	HomeRegular,
	ImageRegular,
	InfoRegular,
	LinkRegular,
	LockClosedRegular,
	MusicNote1Regular,
	OpenRegular,
	PauseRegular,
	PersonRegular,
	PlayRegular,
	QuestionCircleRegular,
	SaveRegular,
	SearchRegular,
	SettingsRegular,
	StopRegular,
	SubtractRegular,
	TimerRegular,
	TranslateRegular,
	WarningRegular,
} from "@fluentui/react-icons";

export const FLUENT_ACTION_ICONS = {
	AddRegular,
	ArrowDownRegular,
	ArrowLeftRegular,
	ArrowResetRegular,
	ArrowRightRegular,
	ArrowUpRegular,
	CheckmarkCircleRegular,
	CheckmarkRegular,
	ChevronDownRegular,
	ChevronLeftRegular,
	ChevronRightRegular,
	ChevronUpRegular,
	ClockRegular,
	CopyRegular,
	CutRegular,
	DeleteRegular,
	DismissRegular,
	DocumentRegular,
	EditRegular,
	ErrorCircleRegular,
	EyeOffRegular,
	EyeRegular,
	FolderOpenRegular,
	HistoryRegular,
	HomeRegular,
	ImageRegular,
	InfoRegular,
	LinkRegular,
	LockClosedRegular,
	MusicNote1Regular,
	OpenRegular,
	PauseRegular,
	PersonRegular,
	PlayRegular,
	QuestionCircleRegular,
	SaveRegular,
	SearchRegular,
	SettingsRegular,
	StopRegular,
	SubtractRegular,
	TimerRegular,
	TranslateRegular,
	WarningRegular,
} satisfies Record<ActionFluentIconNameV0, FluentIcon>;

export const FluentActionIcon = ({ icon }: { icon?: ActionIconV0 }) => {
	if (!icon) return null;
	const Icon = FLUENT_ACTION_ICONS[icon.name];
	return <Icon aria-hidden="true" />;
};
