import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createServer } from "vite";

const root = resolve(import.meta.dirname, "..");
const outputPath = resolve(root, "docs/plugin-protocol-v0.md");
const server = await createServer({
	root,
	appType: "custom",
	logLevel: "silent",
	server: { middlewareMode: true },
});

let protocol: {
	PLUGIN_API_VERSION: number;
	THEME_API_VERSION: number;
	THEME_TOKEN_VERSION: number;
	ALL_CAPABILITIES: readonly string[];
	SCHEMA_CATALOG: Readonly<Record<string, unknown>>;
};
try {
	protocol = await server
		.ssrLoadModule("/packages/plugin-api/src/schema/schemas.ts")
		.then(async (schemas) => {
			const types = await server.ssrLoadModule(
				"/packages/plugin-api/src/types.ts",
			);
			const capabilities = await server.ssrLoadModule(
				"/packages/plugin-api/src/capabilities.ts",
			);
			return { ...types, ...capabilities, ...schemas } as typeof protocol;
		});
} finally {
	await server.close();
}

const sections = Object.entries(protocol.SCHEMA_CATALOG)
	.map(
		([name, schema]) =>
			`## ${name}\n\n<details><summary>JSON Schema</summary>\n\n\`\`\`json\n${JSON.stringify(schema, null, 2)}\n\`\`\`\n\n</details>`,
	)
	.join("\n\n");

const output = `<!-- Generated by scripts/gen-plugin-docs.ts. Do not edit directly. -->
# Plugin Protocol v0

This document is generated from the schemas in
\`packages/plugin-api/src/schema/schemas.ts\`. The TypeScript SDK declarations are
generated by \`pnpm plugin:api:build\`.

| Contract | Version |
| --- | ---: |
| Function Plugin API | ${protocol.PLUGIN_API_VERSION} |
| Theme API | ${protocol.THEME_API_VERSION} |
| Theme tokens | ${protocol.THEME_TOKEN_VERSION} |

## Capabilities

${protocol.ALL_CAPABILITIES.map((capability) => `- \`${capability}\``).join("\n")}

Every manifest, host call, host response, event, document projection, and form is
validated before it crosses the host/plugin boundary. Unknown capabilities and API
versions are rejected. Custom hosts may advertise exact, namespaced capabilities in
the form \`extensions.<reverse-domain>.<name>\`; no wildcard matching is performed.

${sections}
`;

if (process.argv.includes("--check")) {
	let current = "";
	try {
		current = await readFile(outputPath, "utf8");
	} catch {
		// The comparison below reports the missing generated document.
	}
	if (current.replaceAll("\r\n", "\n") !== output) {
		console.error(
			"docs/plugin-protocol-v0.md is out of date; run pnpm plugin:api:build",
		);
		process.exitCode = 1;
	}
} else {
	await writeFile(outputPath, output, "utf8");
	console.log("Generated docs/plugin-protocol-v0.md");
}
